# Enabled will allow the Listener to run, Message is what is displayed when player crafts blocked item, block-all-items name does as implies, items is list of items by name and id that are blocked/banned
enabled: true
message: '&cYou aren''t permitted to craft item %item%'
block-all-items: false
items: []