name: LimitCrafting
main: me.tezk.limitcrafting.LimitCraftingPlugin
version: 4.3-beta
authors: [Tom Micallef, Fang_Shadow]
description: Limit players from crafting items.

commands:
  limitcrafting:
    description: LimitCrafting commands
    aliases: [lc,restrict]

#permissions:
#  limitcrafting.reload:
#    default: op
#  limitcrafting.bypass:
#    default: op
#  limitcrafting.block:
#    default: op
#  limitcrafting.unblock:
#    default: op
#  limitcrafting.list:
#    default: op